 <? $sql_text_aparts = '    SELECT COMPID,CARDNUM,
                            PICCOUNT,
                            COORDN,
                            CONCAT((SELECT VOCSTREET.NAME FROM VOCSTREET WHERE VOCSTREET.ID=STREETID),if(HAAP<>" ",CONCAT(", дом&nbsp;",HAAP), "")) AS STREET,
                            ROOMS,
                            WHAT,
                            (SELECT VOCRAION.NAME FROM VOCRAION WHERE VOCRAION.ID=RAIONID) AS RAION,
                            concat(STAGE, "/", HSTAGE) AS STAGE,
                            concat(TRUNCATE(AAREA,0), "/", TRUNCATE(LAREA,0), "/", TRUNCATE(KAREA,0)) AS AREA,
                            VARIANT,
                            PICTURES,
                            round(PRICE) AS PRICE,
                            (SELECT VOCCITY.NAME FROM VOCCITY WHERE VOCCITY.ID=APARTS.CITYID) AS CITY, 
                            VTOUR,
                            RPLANID,
                            MISC,
                            (SELECT PHONE FROM VOCAGENTS WHERE ID=AGENTID AND VOCAGENTS.COMPID=APARTS.COMPID LIMIT 1) AS PHONE,
                            (select PHOTO from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=APARTS.COMPID limit 1) as PHOTO ,
                            round(SQMPRICE) AS SQMPRICE,
                            DATECOR';
                                
    $sql_text_houses = '    select COMPID,CARDNUM,
                            PICCOUNT,
                            COORDN,
                            CONCAT((SELECT VOCSTREET.NAME FROM VOCSTREET WHERE VOCSTREET.ID=STREETID),if(HAAP<>" ",CONCAT(", дом&nbsp;",HAAP), "")) AS STREET,
                            WHAT,
                            (SELECT VOCRAION.NAME FROM VOCRAION WHERE VOCRAION.ID=RAIONID) AS RAION,
                            HSTAGE AS STAGE,
                            round(AAREA) AS AREA,
                            round(EAREA) AS EAREA,
                            VARIANT,
                            PICTURES,
                            round(PRICE) AS PRICE,
                            (SELECT VOCCITY.NAME FROM VOCCITY WHERE VOCCITY.ID=HOUSES.CITYID) AS CITY,
                            VTOUR,
                            BEDROOMS,
                            (SELECT VOCALLDATA.NAME FROM VOCALLDATA WHERE VOCALLDATA.ID=BTYPEID) as htype,
                            (SELECT VOCALLDATA.NAME FROM VOCALLDATA WHERE VOCALLDATA.ID=USAGEID) as USAGEID,
                            MISC,
                            (select PHONE from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=HOUSES.COMPID limit 1) as PHONE ,
                            (select PHOTO from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=HOUSES.COMPID limit 1) as PHOTO ,
                            round(SQMPRICE) AS SQMPRICE,
                            DATECOR';
                            
    $sql_text_commerc = '   select COMPID,CARDNUM,
                            PICCOUNT,
                            COORDN,
                            CONCAT((SELECT VOCSTREET.NAME FROM VOCSTREET WHERE VOCSTREET.ID=STREETID),if(HAAP<>" ",CONCAT(", дом&nbsp;",HAAP), "")) AS STREET,
                            (SELECT VOCRAION.NAME FROM VOCRAION WHERE VOCRAION.ID=RAIONID) AS RAION,
                            HSTAGE AS STAGE,
                            round(SQUEAR) AS AREA,
                            round(EAREA) AS EAREA,
                            VARIANT,
                            PICTURES,
                            round(PRICE) AS PRICE,
                            (SELECT VOCCITY.NAME FROM VOCCITY WHERE VOCCITY.ID=COMMERC.CITYID) AS CITY,
                            VTOUR,
                            (SELECT VOCALLDATA.NAME FROM VOCALLDATA WHERE VOCALLDATA.ID=OBJID) as OBJ,
                            MISC,
                            (select PHONE from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=COMMERC.COMPID limit 1) as PHONE ,
                            (select PHOTO from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=COMMERC.COMPID limit 1) as PHOTO ,
                            round(SQMPRICE) AS SQMPRICE,
                            DATECOR';
                            
    $sql_text_aparts_new = 'select COMPID,CARDNUM,
                            PICCOUNT,
                            COORDN,
                            CONCAT((SELECT VOCSTREET.NAME FROM VOCSTREET WHERE VOCSTREET.ID=STREETID),if(HAAP<>" ",CONCAT(", дом&nbsp;",HAAP), "")) AS STREET,
                            ROOMS,
                            WHAT,
                            (SELECT VOCRAION.NAME FROM VOCRAION WHERE VOCRAION.ID=RAIONID) AS RAION,
                            concat(STAGE, "/", HSTAGE) AS STAGE,
                            concat(TRUNCATE(AAREA,0), "/", TRUNCATE(LAREA,0), "/", TRUNCATE(KAREA,0)) AS AREA,
                            VARIANT,
                            PICTURES,
                            round(PRICE) AS PRICE,
                            (SELECT VOCCITY.NAME FROM VOCCITY WHERE VOCCITY.ID=APARTS.CITYID) AS CITY,
                            (select NAME from VOCNB where ID=GKID) as GK,
                            VTOUR,
                            RPLANID,
                            MISC,
                            (select PHONE from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=APARTS.COMPID limit 1) as PHONE ,
                            (select PHOTO from VOCAGENTS where ID=AGENTID and VOCAGENTS.COMPID=APARTS.COMPID limit 1) as PHOTO ,
                            round(SQMPRICE) AS SQMPRICE,
                            DATECOR';